import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import Image from "next/image";
import { Bookmark, Compass, Home, HomeIcon, Search, User } from "lucide-react";
import Link from "next/link";
import { Header } from "@/components/header";
//import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next Appㄴㄴㄴㄴ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const [isLoggedIn, setIsLoggedIn] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="sticky top-0 z-50 bg-primary p-4 flex items-center gap-4">
          <MainNav />
          <h1 className="text-xl font-bold text-primary-foreground">TA PASS</h1>
          <div className="ml-auto">
            {isLoggedIn ? (
              <Image
                src="/placeholder.svg"
                alt="Profile"
                width={32}
                height={32}
                className="rounded-full"
              />
            ) : (
              <Link
                href="/login"
                className="text-primary-foreground hover:underline"
              >
                Login
              </Link>
            )}
          </div>
        </header> */}
        <Header />
        {children}
        {/* Bottom Navigation */}
        <div className="fixed bottom-0 left-0 right-0 flex justify-center bg-background">
          <nav className="w-full max-w-[393px] bg-white border-t flex justify-around p-4">
            <button className="flex flex-col items-center">
              <Search className="w-6 h-6" />
              <span className="text-xs mt-1">Search</span>
            </button>
            <button className="flex flex-col items-center">
              <Compass className="w-6 h-6" />
              <span className="text-xs mt-1">Explore</span>
            </button>
            <button className="flex flex-col items-center">
              <Home className="w-6 h-6" />
              <span className="text-xs mt-1">Home</span>
            </button>
            <button className="flex flex-col items-center">
              <Bookmark className="w-6 h-6" />
              <span className="text-xs mt-1">Saved</span>
            </button>
            <button className="flex flex-col items-center">
              <User className="w-6 h-6" />
              <span className="text-xs mt-1">Profile</span>
            </button>
            {/* Safe Area Bottom Spacing */}
            <div className="absolute bottom-0 left-0 right-0 h-safe-bottom bg-white" />
          </nav>
        </div>
      </body>
    </html>
  );
}
